### PR TITLE
Gallery link fix

### PR DESCRIPTION
**Pull request by BermudaVI**
why didnt it work before

### CODE REVIEW

**Comment by BermudaVI** [comment]
im inefficient in making changes

**Comment by gamer0kayf1n3** [comment]
hmm lest see

**Comment by gamer0kayf1n3** [comment]
unfortunately, i would decline this pull request, because I believe you are viewing our site through local means

**Comment by gamer0kayf1n3** [comment]
and local copy means no filesystems that would detect index.html

**Comment by gamer0kayf1n3** [comment]
Please try this out, [https://gamer0kayf1n3.github.io/tagaytay/reviews.html](https://gamer0kayf1n3.github.io/tagaytay/reviews.html), go to the footer part and click the gallery link, and see if this works. If it does, I will decline this pull request because of redundancy.

**Comment by gamer0kayf1n3** [comment]
anyway

**Pull request closed without merging**
